### ISSUE TITLE
Manually choosing featured items

### ISSUE THREAD

**Issue by kbodwin** [hugo-apero/apero#76]
Hello, and thank you for the beautiful template!

This is either a question or a feature request, not sure which. 

I'd like to be able to designate my own featured items on the "About" page, rather than the most recent item being automatically chosen.  Is there a way to do this, or can the option be easily added to check for `featured: true` in the yaml before defaulting to recent posts?

**Comment by apreshill** [comment]
PR here: https://github.com/hugo-apero/hugo-apero/pull/13
